# day05_03_numpy
* 많은 데이터를 하나의 변수에 넣고 데이터를 관리하면 속도도 느리고, 메모리를 많이 차지 함
* 이떄 리스트에 비해 배열은 더 적은 메모리로 더 빠른 속도로 동작 가능

##### 배열의 특징
* 모든 데이터 유형은 전부 같은 데이터 유형
* 원소의 갯수 변경이 불가능


In [3]:
import numpy as np

In [16]:
#numpy를 이용하여 배열
a = np.array([1,2,3,4])
a[0]

1

In [17]:
#배열 연산하기
a + 1

array([2, 3, 4, 5])

In [9]:
b = [1,2,3,4]
b[0]

1

In [18]:
for i in b:
    print(i+1)

2
3
4
5


In [20]:
a * 2

array([2, 4, 6, 8])

In [22]:
a == 1

array([ True, False, False, False])

In [26]:
#특정 갯수의 배열 만들기
np.arange(100) # 0 부터 100전까지
c = np.arange(1,100) # 1 부터 100전까지


In [28]:
c[0:10]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#c 에서  나온 2, 4, 30번 방 조회하기
c[[2,4,30]]

array([ 3,  5, 31])

In [34]:
#c에서 짝수인 방만 조회
c[c%2==0]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68,
       70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [39]:
#모양확인하기
a = np.array([1,2,3])
print(a.shape)
a = np.array([[1,2,3],[4,5,6]])
print(a.shape) #2행 3열  

(3,)
(2, 3)


In [40]:
a[1,2]

6